const EXPECTED_DB_VERSION="0.3.3";
const REMOTE_BASE="https://kensukesuga86.github.io/Nicole-Astronomy-Database/versions/0.3.3/";
const LOCAL_BASE="./database/";
const DATA_NAMES=["constellations","stars","planets","deep-sky","asterisms","catalog","external-sources","solar-system","constellation-standard","constellation-line-stars"];

async function fetchJson(base,path){const r=await fetch(base+path,{cache:"no-store"});if(!r.ok)throw new Error(`${path} HTTP ${r.status}`);return r.json()}
async function loadDb(base){const manifest=await fetchJson(base,"manifest.json");if(manifest.database_version!==EXPECTED_DB_VERSION)throw new Error(`DB version mismatch: ${manifest.database_version}`);const values=await Promise.all(DATA_NAMES.map(n=>fetchJson(base,`data/${n}.json`)));const db={manifest};DATA_NAMES.forEach((n,i)=>db[n.replaceAll("-","_")]=values[i]);if(!Array.isArray(db.constellations)||db.constellations.length!==88)throw new Error("88星座DBではありません");if(!Array.isArray(db.deep_sky)||db.deep_sky.filter(x=>Number(x.messier_number)>=1&&Number(x.messier_number)<=110).length!==110)throw new Error("M1-M110が揃っていません");return db}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function storyHtml(e){if(!e)return"";if(e.raw_html)return e.raw_html;const parts=[["概要",e.overview],["観測のポイント",e.observing],["天文学的な見どころ",e.science],["歴史・名前",e.history]].filter(x=>x[1]);return parts.map(([h,t])=>`<div class="story-topic"><h4>${esc(h)}</h4><p>${esc(t)}</p></div>`).join("")}
function pendingStory(o){const cat=o.catalog_metadata||{},bits=[];if(o.constellation_id)bits.push(`星座：${esc(o.constellation_id)}`);if(Number.isFinite(Number(o.magnitude_v)))bits.push(`等級：約${esc(o.magnitude_v)}`);if(o.size_text)bits.push(`見かけの大きさ：${esc(o.size_text)}`);if(cat.source_type_label_ja)bits.push(`種類：${esc(cat.source_type_label_ja)}`);return `<div class="story-topic"><h4>カタログ情報</h4><p>${bits.join(" / ")||"基本カタログ情報を収録しています。"}</p></div><div class="story-topic"><h4>解説</h4><p>情報準備中</p></div>`}
function legacy(db){
 const allMonths=[1,2,3,4,5,6,7,8,9,10,11,12];
 const CONSTELLATIONS=db.constellations.map(c=>({id:c.id,name:c.name?.ja||c.id,en:c.name?.en||"",abbr:c.name?.abbr||c.id,season:c.season||"",months:c.visible_months_legacy||allMonths,stars:c.main_stars_text||"",story:c.legacy_story||"",science:c.explanation?.science||"",myth:c.explanation?.myth||""}));
 const CONSTELLATION_TEXT=Object.fromEntries(db.constellations.map(c=>[c.id,{science:c.explanation?.science||"",myth:c.explanation?.myth||""}]));
 const CONST_COORD=Object.fromEntries(db.constellations.map(c=>[c.id,[Number(c.representative_position?.ra_deg),Number(c.representative_position?.dec_deg)]]));
 const STARS_DB=db.stars.filter(x=>x.roles?.includes("curated_object")).map(o=>({id:o.id,name:o.name?.ja_full||o.name?.ja||o.id,type:"star",icon:o.icon||"⭐",cat:o.catalog_category||"恒星",ra:Number(o.position?.ra_deg),dec:Number(o.position?.dec_deg),mag:o.magnitude_v==null?99:Number(o.magnitude_v),dist:o.distance_text||"",size:o.size_text||"",scope:o.recommended_magnification||"",highlight:o.highlight||"",months:o.visible_months_legacy?.length?o.visible_months_legacy:allMonths,story:storyHtml(o.explanation)||pendingStory(o),bv:o.photometry?.bv??null,spectral_type:o.photometry?.spectral_type??null,display_color_hex:o.photometry?.display_color_hex??null}));
 const planets=db.planets.map(o=>({id:o.id,name:o.name?.ja||o.id,type:"planet",icon:o.icon||"●",cat:o.catalog_category||"惑星",planet:o.position?.planet_key||o.id,mag:o.magnitude_v==null?99:Number(o.magnitude_v),dist:o.distance_text||"",size:o.size_text||"",scope:o.recommended_magnification||"",highlight:o.highlight||"",months:o.visible_months_legacy||[],story:storyHtml(o.explanation)||pendingStory(o),physical_diameter_km:o.physical_diameter_km??null}));
 const deep=db.deep_sky.map(o=>({id:o.id,name:o.name?.ja||o.id,type:o.type,icon:o.icon||"✦",cat:o.catalog_category||"",ra:Number(o.position?.ra_deg),dec:Number(o.position?.dec_deg),mag:o.magnitude_v==null?99:Number(o.magnitude_v),dist:o.distance_text||"",size:o.size_text||"",scope:o.recommended_magnification||"",highlight:o.highlight||"",months:o.visible_months_legacy?.length?o.visible_months_legacy:allMonths,story:storyHtml(o.explanation)||pendingStory(o),constellation:o.constellation_id||null,aliases:o.aliases||[],messier_number:o.messier_number||null,catalog_metadata:o.catalog_metadata||null,angular_size:o.angular_size||null}));
 const SKY_EXTRA_STARS=db.stars.filter(x=>x.source?.dataset==="SKY_EXTRA_STARS").map(o=>({id:o.id,name:o.name?.ja||o.id,ra:Number(o.position?.ra_deg),dec:Number(o.position?.dec_deg),mag:o.magnitude_v==null?6:Number(o.magnitude_v),bv:o.photometry?.bv??null,display_color_hex:o.photometry?.display_color_hex??null}));
 const allStars=Object.fromEntries(db.stars.map(x=>[x.id,x])),SKY_ASTERISM_STARS={};for(const a of db.asterisms)for(const id of a.star_ids||[]){const o=allStars[id];if(o)SKY_ASTERISM_STARS[id]={name:o.name?.ja||id,ra:Number(o.position?.ra_deg),dec:Number(o.position?.dec_deg)}}
 const SKY_ASTERISMS=db.asterisms.map(a=>({name:a.name?.ja||a.id,stars:a.star_ids||[],lines:(a.lines||[]).map(x=>[x.from,x.to])}));
 const SKY_STAR_CONSTELLATION_MAP=Object.fromEntries(db.stars.filter(x=>x.constellation_id).map(x=>[x.id,x.constellation_id]));
 for(const c of db.constellation_standard||[])for(const id of c.line?.star_ids||[])if(!SKY_STAR_CONSTELLATION_MAP[id])SKY_STAR_CONSTELLATION_MAP[id]=c.id;
 const SKY_CONSTELLATION_STANDARD=(db.constellation_standard||[]).map(c=>({name:c.name?.ja||c.id,abbr:c.name?.abbr||c.id,lines:(c.line?.segments||[]).map(x=>[x.from,x.to])}));
 const SKY_STANDARD_LINE_STARS=Object.fromEntries((db.constellation_line_stars||[]).filter(x=>x.ra_deg!=null&&x.dec_deg!=null&&Number.isFinite(Number(x.ra_deg))&&Number.isFinite(Number(x.dec_deg))).map(x=>[x.id,{id:x.id,hip:x.hip??null,name:x.name||null,ra:Number(x.ra_deg),dec:Number(x.dec_deg),mag:x.magnitude_v==null?6:Number(x.magnitude_v)}]));
 const SKY_STANDARD_LINE_STAR_REFERENCES=(db.constellation_line_stars||[]).filter(x=>x.coordinate_status==="upstream_reference");
 return{CONSTELLATIONS,CONSTELLATION_TEXT,CONST_COORD,STARS_DB,DSO_DB:[...planets,...deep],SKY_EXTRA_STARS,SKY_ASTERISM_STARS,SKY_ASTERISMS,SKY_STAR_CONSTELLATION_MAP,SKY_CONSTELLATION_STANDARD,SKY_STANDARD_LINE_STARS,SKY_STANDARD_LINE_STAR_REFERENCES};
}
function loadClassic(src){return new Promise((resolve,reject)=>{const el=document.createElement("script");el.src=src;el.async=false;el.onload=resolve;el.onerror=()=>reject(new Error(`script load failed: ${src}`));document.body.appendChild(el)})}
(async()=>{let db=null,source="";for(const [kind,base] of [["online",REMOTE_BASE],["local",LOCAL_BASE]]){try{db=await loadDb(base);source=kind;break}catch(err){console.warn(`Nicole common DB ${kind} load failed`,err)}}if(db){window.NICOLE_COMMON=legacy(db);window.NicoleAstronomyDatabase=db;window.NicoleAstronomyDatabaseMeta={version:db.manifest.database_version,source}}else{window.NICOLE_COMMON=null;window.NicoleAstronomyDatabaseMeta={version:"legacy-embedded",source:"embedded"}}await loadClassic(`./app.js?v=2.1.4`)})().catch(err=>{console.error("Nicole bootstrap failed",err);loadClassic(`./app.js?v=2.1.4`) });
